---@class ScratchCache
---@field cache table<string, string>
---@field load fun()
---@field save fun()
---@field set fun(value: string)
---@field get fun(): string?

---@class ScratchOpts
---@field buffer_name string?
---@field cache_path string?
---@field save_delay integer?
---@field dont_save boolean?
---@field default_content string?

---@class ScratchConfig
---@field buffer_name string?
---@field cache_path string?
---@field save_delay integer?
---@field dont_save boolean?
---@field default_content string?
---@field validate fun(opts: ScratchOpts?)
